### PR TITLE
Update deprecated circleci images to latest

### PR DESCRIPTION
**Pull request by yorinasub17**
Update deprecated circleci images to latest

### CODE REVIEW

**Review by zackproser — COMMENTED** [review]
LGTM

**Comment by rhoboat** [comment]
LGTM! @yorinasub17

**Review by rhoboat — APPROVED** [review]

**Comment by rhoboat** [comment]
It's not the latest now, but I'd be ok to merge and do a followup.

**Comment by yorinasub17** [comment]
Thanks for review. Merging now.

**Pull request merged**
